# Generated by Django 5.1.3 on 2024-11-14 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('famous_name', models.CharField(blank=True, max_length=50, null=True)),
                ('income', models.PositiveBigIntegerField()),
                ('career_start', models.DateField()),
                ('career_end', models.DateField(blank=True, null=True)),
                ('total_movies', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'actor_info',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('famous_name', models.CharField(blank=True, max_length=50, null=True)),
                ('income', models.PositiveBigIntegerField()),
                ('career_start', models.DateField()),
                ('career_end', models.DateField(blank=True, null=True)),
                ('total_movies', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'director_info',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('famous_name', models.CharField(blank=True, max_length=50, null=True)),
                ('income', models.PositiveBigIntegerField()),
                ('career_start', models.DateField()),
                ('career_end', models.DateField(blank=True, null=True)),
                ('total_movies', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'producer_info',
                'abstract': False,
            },
        ),
    ]
