# Generated by Django 5.1.3 on 2024-11-16 12:08

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moviemakers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
                ('industry_name', models.CharField(max_length=30, unique=True)),
                ('country', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'movie_industry',
                'ordering': ['-country'],
                'indexes': [models.Index(fields=['country', 'language'], name='combine_idx'), models.Index(fields=['language'], name='lang_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('country'), django.db.models.functions.text.Lower('language'), name='contry_language')],
            },
        ),
        migrations.CreateModel(
            name='ProductionHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_name', models.CharField(db_column='name', max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_house', to='movies.movieindustry')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_house', related_query_name='p_house', to=settings.AUTH_USER_MODEL)),
                ('partners', models.ManyToManyField(related_name='prhouse_partner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'production_house',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('bugget', models.BigIntegerField()),
                ('total_collection', models.BigIntegerField(blank=True, null=True)),
                ('release_date', models.DateField()),
                ('actors', models.ManyToManyField(related_name='movie_act', to='moviemakers.actor')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movie_dir', to='moviemakers.director')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movie_industry', to='movies.movieindustry')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movie_producer', to='moviemakers.produrer')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movie_prod', to='movies.productionhouse')),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
